name: Node CI

# Create a github actions workflow with 2 jobs, the first of which is a matrix job and the second that depends on the matrix job and uses its results

on:
    push:
        branches-ignore:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            location: ${{ steps.set-outputs.outputs.location }}
        strategy:
            matrix:
                code_location:
                    - "location_1"
                    - "location_2"
                    - "location_3"
        steps:
            - uses: actions/checkout@v3
            - name: Set Outputs
              id: set-outputs 
              run: |
                echo "location=${{ matrix.code_location }}" >> "$GITHUB_OUTPUT"
    
    test:
        runs-on: ubuntu-latest
        needs: ${{ matrix.code_location }}
        strategy:
          matrix:
            code_location: ${{ fromJson(needs.build.outputs.outputs) }}
        steps:
            - uses: actions/checkout@v3
            - name: Verify Outputs
              run: |
                echo "location=${{ matrix.code_location }}"