name: Node CI

on: 
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.set-outputs.outputs.name }}

    steps:
      - uses: actions/checkout@v3
      - name: Set Outputs
        id: set-outputs
        run: |
          echo "name=public" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
  test:

    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v3
    - name: Verify Outputs
      run: |
        echo "NAME=${{ needs.build.outputs.name }}"